### ISSUE TITLE
When tomcat dependency groups is missing invoking tomcat target throws a NPE

### ISSUE THREAD

**Issue by robotdan** [savant-build/tomcat-plugin#1]
Consider the following build file

``` groovy
project(group: "foo", name: "bar", version: "0.1.0", licenses: ["Commercial"]) {

  ...
  dependencies {
     ...
  }
}

tomcat.settings.foo=somevalue
tomcat.settings.bar=someothervalue

target(name: "tomcat") {
  tomcat.build()
}
```

Notice the dependencies does not contain a group named `tomcat`.

``` bash
$ sb tomcat --debug
...

:[tomcat]:
Resolving ArtifactGraph with a root of [com.inversoft.usermgmt:inversoft-user-management:inversoft-user-management:0.1.0:jar]
Build failed due to an exception or error.
java.lang.NullPointerException
    at org.savantbuild.util.HashGraph.find(HashGraph.java:289)
    at org.savantbuild.util.HashGraph.find(HashGraph.java:117)
    at org.savantbuild.dep.graph.ResolvedArtifactGraph.getPath(ResolvedArtifactGraph.java:47)
    at org.savantbuild.dep.graph.ResolvedArtifactGraph$getPath.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.savantbuild.plugin.dep.DependencyPlugin.path(DependencyPlugin.groovy:204)
    at org.savantbuild.plugin.dep.DependencyPlugin$path.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.savantbuild.plugin.tomcat.TomcatPlugin.build(TomcatPlugin.groovy:56)
    at org.savantbuild.plugin.tomcat.TomcatPlugin$build.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at build$_run_closure9.doCall(build.savant:147)
    at build$_run_closure9.doCall(build.savant)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:417)
    at groovy.lang.Closure.run(Closure.java:504)
    at org.savantbuild.runtime.DefaultProjectRunner.runTarget(DefaultProjectRunner.java:95)
    at org.savantbuild.runtime.DefaultProjectRunner.lambda$run$5(DefaultProjectRunner.java:89)
    at org.savantbuild.runtime.DefaultProjectRunner$$Lambda$38/1234250905.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1234)
    at org.savantbuild.runtime.DefaultProjectRunner.run(DefaultProjectRunner.java:72)
    at org.savantbuild.runtime.DefaultBuildRunner.run(DefaultBuildRunner.java:81)
    at org.savantbuild.runtime.Main.main(Main.java:67)
```

Adding the tomcat dependency to the dependencies group resolves the problem.

``` groovy
group(name: "tomcat") {
  dependency(id: "org.apache.tomcat:apache-tomcat:8.0.12:tar.gz")
}
```

I would have expected to get a dependency failure instead of a NPE.

**Comment by voidmain** [comment]
Finally fixed this one. It will be in the next release. Likely 0.4.5.
